---
name: reset
match: ^hey barney reset$
run: ros2 run pyrobosim_ros barn_commands.py --ros-args -p mode:=dock
---
name: start
match: ^hey barney start$
run: ros2 run pyrobosim_ros barn_commands.py --ros-args -p mode:=dock
---
name: next
match: ^hey barney next$
run: ros2 run pyrobosim_ros barn_commands.py --ros-args -p mode:=
---
name: yes
match: ^hey barney yes$
run: ros2 run pyrobosim_ros barn_commands.py --ros-args -p mode:=
---
name: no
match: ^hey barney no$
run: ros2 run pyrobosim_ros barn_commands.py --ros-args -p mode:=
